#!/bin/bash
scriptDir=$(dirname -- "$(readlink -e -- "$BASH_SOURCE")")
algol16 "$scriptDir/test-$1.algol16" "$scriptDir/test-$1.sextium"
echo "$scriptDir/test-$1.sextium"
sextium "$scriptDir/test-$1.sextium"
# rm "test-$1.sextium"
